### ISSUE TITLE
temperature sensor could read negative values...

### ISSUE THREAD

**Issue by krikk** [Apollon77/I2CSoilMoistureSensor#1]
according to the schematic the i2cSoilMoistureSensor uses an NCP18XH103F03RB (http://www.mouser.at/ProductDetail/Murata-Electronics/NCP18XH103F03RB/?qs=k3rQb2PKXqkF9YvF09qsvw%3D%3D) for temperature measurement, this sensor can measure values down to -40 °C according to the datasheet... with my raspberry pi example code negative values are reported correctly (see https://github.com/Miceuz/i2c-moisture-sensor#raspberry-pi-example) ...perhaps you could adapt your library to also allow negativ temp. values..

thx

...i would have submitted a patch, but my arduino programming skills are not that good... (still learning the basics)

**Comment by Apollon77** [comment]
Yes ... did not tested the sensor in negative areas :-) Will need to do.
And I change temperature to a signed value

**Comment by Apollon77** [comment]
Have already changed it locally and will test by tomorrow evening ... stay tuned for first update and first official release :-))

**Comment by Apollon77** [comment]
see 1.0.0 :-))
