### ISSUE TITLE
PlatformIO GCC error in Linter

### ISSUE THREAD

**Issue by genestealer** [Apollon77/I2CSoilMoistureSensor#13]
For some reason, GCC error is giving an error in Linter.
> I2CSoilMoistureSensor.h: No such file or directory

However the program is still compiling and working fine, but the error is of annoyance.

Info:
I2CSoilMoistureSensor has been added in the project PlatformIO Library Manager as per instructions: http://platformio.org/lib/show/294/I2CSoilMoistureSensor/examples

platform.ini
```
[env:nodemcuv2]
platform = espressif8266_stage
board = nodemcuv2
framework = arduino
lib_deps = PubSubClient, ArduinoJson, I2CSoilMoistureSensor
```
Any ideas how I can debug this?

**Comment by Apollon77** [comment]
Hi,

sorry, but because I personally do not use PlatformIO I have no idea how to help here ...
